version: "3"
services:
  initializer:
    image: 'bitnami/kafka:latest'
    entrypoint: '/bin/bash'
    command: >
      -c "sleep 15 ;
      kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 2 --topic flows ;"

  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build: ../grafana
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./grafana/datasources-ch.yml:/etc/grafana/provisioning/datasources/datasources-ch.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  db:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
    volumes:
      - ./clickhouse:/docker-entrypoint-initdb.d/
      - ../pb-ext/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
