version: "3"
services:
  mocker2:
    build:
      context: ../
      dockerfile: Dockerfile.mocker
    restart: always
    command: >
      -kafka.brokers kafka:9092 -kafka.topic flows -proto.fixedlen=true -loglevel=debug
